version: "3"
services:
  postgresdb:
    image: postgres:15.2-alpine
    container_name: postgresdb
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: Morpion
      POSTGRES_USER: morpion
      POSTGRES_PASSWORD: Morpion1234

    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - 127.0.0.1:8080:8080
  
  server:
    image: node:latest
    container_name: server
    restart: always
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - server/.env.local
    
  client:
    image: node:latest
    container_name: client
    restart: always
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - 127.0.0.1:5173:5173