version: '3'
services:
  postgresdb:
    image: postgres:15.2-alpine
    container_name: postgresdb
    ports:
      - '127.0.0.1:${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: Morpion
      POSTGRES_USER: morpion
      POSTGRES_PASSWORD: Morpion1234

    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - 127.0.0.1:8080:8080